### ISSUE TITLE
How to edit the self defined json  to send

### ISSUE THREAD

**Issue by jerry-yu** [aa24615/websocket-pressure-test#2]
How to edit the self defined json  to send

**Comment by jerry-yu** [comment]
Maybe a example json file is better

**Comment by aa24615** [comment]
> Maybe a example json file is better

Any JSON file

**Comment by jerry-yu** [comment]
Ok, i tried  and use tcpdump get the sending message. It's work

**Comment by jerry-yu** [comment]
another question: the json file content only send once per connection
How to send file contents regularly？

**Comment by aa24615** [comment]
> another question: the json file content only send once per connection How to send file contents regularly？

Edit the file src/websocket-pressure-test.js at line 86
